[package]
name = "basis32"
version = "0.1.0"
edition = "2021"

[features]
default = ["alloc", "std"]
alloc = []
std = []

[dependencies]

[dev-dependencies]
arbitrary = "1.4.1"
arbtest = "0.3.2"
criterion = "0.5.1"

[[bench]]
name = "encode"
harness = false
