---
name: CI
on: [push]
env:
  RUST_BACKTRACE: 1
  # Run each test for 5 seconds.
  ARBTEST_BUDGET_MS: 5000
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Test
        run: cargo test --workspace --all-targets --all-features
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Test
        run: cargo test --workspace --all-targets --all-features
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Test
        run: cargo test --workspace --all-targets --all-features
  publish:
    needs: [ubuntu, macos, windows]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish --quiet --package base32-fs
